# Generated by Django 3.2 on 2021-04-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_entry_like_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='like_num',
            field=models.IntegerField(default=0, null=True, verbose_name='点赞数'),
        ),
    ]
